version: '3.7'

services:
  app_list_server:
    build:
      context: ./app_list_server
    volumes:
      - ./app_list_server:/app
    command: node_modules/nodemon/bin/nodemon.js -w /app /app/src/index.js
