version: '3.7'

services:
  app_list_server:
    build:
      context: ./app_list_server
    volumes:
      - ./app_list_server:/app
    command: node_modules/nodemon/bin/nodemon.js -w /app /app/src/index.js
    ports:
      - 3000:3000

  app_list_server_lint:
    build:
      context: ./app_list_server
    volumes:
      - ./app_list_server:/app
    command: ./node_modules/.bin/eslint .

  app_list_server_tests:
    build:
      context: ./app_list_server
    volumes:
      - ./app_list_server:/app
    command: ./node_modules/.bin/ava
